### ISSUE TITLE
Error while selecting the Tax report for the whole year 2021

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1328] opened 2022-04-20 11:35 UTC
**Describe the bug**
Received the attached error while selecting the Tax report for the whole year 2021. Please check and fix the issue.

**Screenshots**

<img width="1377" alt="Screenshot 2022-04-20 at 5 03 43 PM" src="https://user-images.githubusercontent.com/16541548/164221720-097571b6-c086-47ad-8d1f-ba17e872215f.png">

<img width="1185" alt="Screenshot 2022-04-20 at 5 01 17 PM" src="https://user-images.githubusercontent.com/16541548/164221739-e6861704-56d2-4e43-b595-afa2f9a24938.png">

**Comment by dsajwan2020** [comment] 2022-04-21 06:26
Hi Mohit,

I am looking into this issue I have requested access to production environment logs of employee portal.

Some of the reason that cause this issue are

-There mainly cause due to permission issues
-Environment variables not found or .env file not found on your root directory
-PHP extensions problem
-Database problem
- Server request handling error
I can conclude the specific cause once  I get access to logs.

Till then can you confirm if this issue is reoccurring

**Comment by dsajwan2020** [comment] 2022-04-21 07:59
As per investigation of laravel-2022-04-20.log  file following is the causes this error

![image](https://user-images.githubusercontent.com/96309135/164407168-6131e34e-1ba2-4e50-ab57-981f20aee8cc.png)

 The error is from tax-report.blade.php file line #64  <td>{{ number_format($invoice->tds, 2) }}</td>

**Comment by mohitsharma-22** [comment] 2022-04-21 13:28
@dsajwan2020 Thanks for checking in. I confrim the issue is still there and I am able to replicate it.

Please do the below steps to replicate it.
1. Select the **Monthly tax report** from **Finance** dropdown.
2. Select below from the report dropdowns.
- Region = All-Region
- Year = 2021
- Month = All Months
- Status = All Status
It will throw the 500 error message on the screen

**Comment by dsajwan2020** [comment] 2022-04-23 10:42
Hi mohit the issue fix has been incorporated in the production environment. Can you please confirm is the issue fixed in production environment.

**Comment by mohitsharma-22** [comment] 2022-04-23 14:08
@dsajwan2020 I am not able to test this right now. My access to production is removed.  I will test it once my access is resumed.

**Comment by dsajwan2020** [comment] 2022-04-25 11:22
Hi @mohitsharma-22 can you please confirm that is this issue resolved in production environment.

**Comment by mohitsharma-22** [comment] 2022-04-25 12:39
@dsajwan2020 Yes, I am able to export the report now from Portal. Thanks.

**Comment by dsajwan2020** [comment] 2022-04-25 13:03
Closing this issue as it is fixed with PR https://github.com/ColoredCow/portal/pull/1329

**Closed by dsajwan2020** 2022-04-25 13:03 UTC
Labels: priority : high !!, module : finance
