### ISSUE TITLE
User is not able to access finance module if the user is assigned permission for finance module.

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1333] opened 2022-04-25 11:36 UTC
**Describe the bug**
If the user is assigned permission to access finance module through user management in employee portal . The user is not able to access finance module. 

**To Reproduce**
1. Login to employee portal
2. Click on the settings

![image](https://user-images.githubusercontent.com/96309135/165080931-51b5dd59-1466-44c0-8f9f-f829d9d2ad7b.png)
  

3.  Scroll down to user Management

![image](https://user-images.githubusercontent.com/96309135/165080965-b38c48c6-c10d-451f-9b4e-489c95b29cd7.png)

4. Enable Finance in from the list of modules

![image](https://user-images.githubusercontent.com/96309135/165081048-6c2a2ac1-c63f-41b3-bf3f-4560209187b8.png)

5. User not able to access Finance module in employee portal

![image](https://user-images.githubusercontent.com/96309135/165081260-5a5f5503-d81b-491b-9628-6a883ddda9d8.png)
 

**Expected behavior**
A user should be able to access the finance module

**Comment by dsajwan2020** [comment] 2022-05-07 08:20
To fix this issue we need to implemet user access policy [#1337](https://github.com/ColoredCow/portal/issues/1337)

**Comment by rathorevaibhav** [comment] 2023-06-24 12:23
This is a duplicate of #1337 which has been resolved. Closing this.

**Closed by rathorevaibhav** 2023-06-24 12:23 UTC
Labels: type : bug 🐛, module : finance
