### ISSUE TITLE
Load books image over HTTPS

### ISSUE THREAD

**Issue by bohraji** [ColoredCow/portal#375] opened 2018-06-06 07:23 UTC
<img width="1674" alt="screen shot 2018-06-06 at 12 53 15" src="https://user-images.githubusercontent.com/12884297/41022950-a92054d8-6988-11e8-8af5-7db8e8a1b553.png">

**Comment by lalitmehta933** [comment] 2018-07-31 07:49
@bohraji can you tell me more about what I have to do in this task.

**Comment by lalitmehta933** [comment] 2018-08-01 06:07
So basically the issue is that our page is loading in https but the images we use for books are loading in http. So we have to load our images that we add over https.

**Comment by rathorevaibhav** [comment] 2021-09-22 13:38
This seems to be done. Closing.

**Closed by rathorevaibhav** 2021-09-22 13:38 UTC
Labels: status : development, good first issue, module : books
