### ISSUE TITLE
Multiple options for on-hold email

### ISSUE THREAD

**Issue by P4NK4J** [ColoredCow/portal#2177] opened 2022-08-11 17:03 UTC
**Describe the task**
While we put an application on hold, we have a commented functionality to send them emails from the on-hold template. We need a feature to select emails from two different options. You need to perform the following tasks:

- [x] Figure out the current putting an application on-hold implementation in the codebase. Get familiarity with the events triggered and emails sent. We do have an existing on-hold email template. Change its label to `On Hold email to the applicant - option 1` and update its content to the following in seeders file.

```
Dear |*applicant_name*|,

Thanks for applying to ColoredCow for the position |*job_title*|.We have put your application into consideration. Some skills match our requirements and some are missing. Your application is kept on hold and we will reach out to you if there are any possibilities we can explore together.
Thanks,

HR Team,
ColoredCow
```

- [x] Create a similar email template through seeder, and its label should read `On hold email to applicant - option 2`

- [x] When we click `put on hold` button, a popup appears for confirmation. In this Popup, there should be an option to select `send mail` (refer to screenshot below). If send mail is checked, we want the following two different tabs to appear, saying `option 1` and `option 2`. These should be bootstrap tabs
- [x] Clicking on `option 1`, the option 1 email template should appear in an editor, and same goes for `option 2` tab click. The editor should look something like. When `send mail` check is clicked, by default option 1 email template should appaer.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/35001775/184191758-9b1ba894-8134-46dd-8200-efcd0b702e72.png">

- [x] Clicking on confirm, the corresponding email should go to applicant.

**Comment by GauravGusain98** [comment] 2022-08-27 07:24
### Action items

- [ ] Setup mailtrap. You can take reference from portal installation guide
- [ ] Create Mail file inside the `/mail` folder for the Sending the mail. [Reference](https://laravel.com/docs/8.x/mail#generating-mailables)
- [ ] When submitting the form, check if you are getting the correct subject and body in the request.
- [ ] IN the controller call the mail file class you just created. Check other files to see how to call the mail class.
- [ ] Inside the mail file fetch the subject and body from the request and pass them in the mail setting. Take reference from other mail files
- [ ] For adding body to subject you need to use the approach from the mails files inside the invoice module
- [ ] Try sending the mail. In case it shows error just use `dd()` to debug each line and see where the issue is coming

**Comment by Ayush8923** [comment] 2023-06-25 05:19
This issue is completed. Closing it.

**Closed by Ayush8923** 2023-06-25 05:19 UTC
Labels: module : hr, Points: 2
